version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: docker/dev/Dockerfile
        networks:
          - development
        expose:
          - "8000"
        env_file:
          - .env
        volumes:
          - .:/mergeminion
    ngrok:
        image: 'ngrok/ngrok:alpine'
        environment:
            NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
            NGROK_DEBUG: true
        command: 'http app:8000 --log stdout --log-level info | grep -Eoh "https.+\.ngrok\.io" --line-buffered | awk "{print "Proxy address: " $0; fflush("/dev/stdout")}"'
        ports:
            - '4551:4551'
        depends_on:
          - app
        expose:
            - '4551'
        networks:
          - development
networks:
  development:
    driver: bridge